name: GitHub Actions Secret Example

on: [workflow_dispatch]

jobs:
  secrets-in-github-actions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Echo the secret
      run: |
          echo "dumping to file"
          ls -la
          echo ${{ secrets.APP_SECRETS }} | base64 -d > secret_file
          ls -la
          cat secret_file
