name: GitHub Actions Secret Example

on: [workflow_dispatch]

jobs:
  secrets-in-github-actions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Echo the secret
      run: |
        echo $secret | sed "s/:\s/:temp/g;s/\s/\n/;s/ /\n/g;s/temp/ /g" > ./secret.txt
        cat ./secret.txt
      env:
          secret: ${{ secrets.APP_SECRETS }}
