name: GitHub Actions Secret Example

on: [workflow_dispatch]

jobs:
  secrets-in-github-actions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Echo the secret
      run: |
        echo "Printing the environment variable"
        echo ${{secrets.APP_SECRETS}} | sed 's/./& /g'
        echo "dumping to file"
